### ISSUE TITLE
Add new publishing method and mode

### ISSUE THREAD

**Issue by feidens** [cryptimeleon/math#55]
The goal is to publish via github actions to maven central via the open source offering of [ossrh](https://central.sonatype.org/pages/ossrh-guide.html).

The **question** is whether we stick to the current mode @rheitjoh @JanBobolz.
The current publishing mode is `publish on: push on branch: release`.

### Pros
* we can protect the branch
* we can establish that we review the pull requests for the release branch. Therefore forcing us to stick to our versioning scheme

### Cons
* ?

**Comment by JanBobolz** [comment]
I like the current mode. 

Do we set up an extra branch for major release features? Without something like that, I see the following problem: 

- (1) someone develops an API-breaking new feature and pushes it to master. 
- (2) Someone develops a hotfix (unrelated to (1)) and pushes it to master. 
- (3) => We cannot merge master onto release without having to bump the major version. 

With this, users of the library would be forced to adopt API-breaking changes relatively often. I'd like to stagger releases in the sense that we bundle a bunch of API-breaking changes into one release ("make it count") so that major version bumps don't happen so often (and/or I'm not forced to instantly adopt new major versions because old versions were buggy).

**Comment by rheitjoh** [comment]
[Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) might be worth looking into in regards to branching models.

**Comment by feidens** [comment]
Okay git flow is always good and fits our needs perfectly.
* I suggest that we then change our model to `publish on: merge from branch: release-x.y to master`.
* Could also end up being `publish on: tag x.y.z on master`, where the tag is only created after a merge from a release-x.y.z branch to master.

**Comment by JanBobolz** [comment]
I'd prefer keeping to our current terminology instead of redoing *everything*, i.e. their "master" is our "release" and their "develop" is our "master". Unless we want to hardcore adopt everything from git flow, then it may be easier for other collaborators to stick to their naming (which I'd  also be okay with).

As to tagging vs just pushing to release - sure, why not?

**Comment by feidens** [comment]
Collaborators will usually be confused by our "non-standard" master, develop branch usage.

Hence I vote for an overhaul of the terminology.

**Comment by JanBobolz** [comment]
Alright. Then let's go for "main" and "develop".

**Comment by feidens** [comment]
You mean master and develop?

**Comment by JanBobolz** [comment]
No. Default branch name on github is now `main`. `master` is being phased out in many projects. If we're already renaming branches, we might as well adapt the "PC" version.

**Comment by feidens** [comment]
Ah right, I forgot about that.

**Comment by feidens** [comment]
closed with #65
