### ISSUE TITLE
Rename CountingGroup to DebugGroup

### ISSUE THREAD

**Issue by JanBobolz** [cryptimeleon/math#96]
Plus advertise the group better in documentation.

**Comment by rheitjoh** [comment]
The renaming is addressed by #97.

**Comment by rheitjoh** [comment]
The documentation page also requires all the counting group mentions to be changed to debug group. Since that is specific to the next unreleased version, I would prefer to first address [this issue](https://github.com/cryptimeleon/cryptimeleon.github.io/issues/6) regarding adding a version selector to the documentation. That way we don't update the docs in a way that does not fit with the current release.

**Comment by rheitjoh** [comment]
Addressed by https://github.com/cryptimeleon/cryptimeleon.github.io/pull/14
